/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApartmentFilter: typeof import('./components/filter/apartment-filter.vue')['default']
    ApartmentItem: typeof import('./components/apartment/apartment-item.vue')['default']
    ApartmentList: typeof import('./components/apartment/apartment-list.vue')['default']
    BuildObjectDetail: typeof import('./components/objects/build-object-detail.vue')['default']
    BuildObjectList: typeof import('./components/objects/build-object-list.vue')['default']
    BuyApartmentForm: typeof import('./components/site/form/buy-apartment-form.vue')['default']
    BuyApartmentModal: typeof import('./components/site/modal/buy-apartment-modal.vue')['default']
    CheckboxDropdown: typeof import('./components/filter/part/checkbox-dropdown.vue')['default']
    ContactPersonalManager: typeof import('./components/site/modal/contact-personal-manager.vue')['default']
    CreateAgentModal: typeof import('./components/site/modal/create-agent-modal.vue')['default']
    CreateManagerModal: typeof import('./components/site/modal/create-manager-modal.vue')['default']
    CreateStudentModal: typeof import('./components/site/modal/create-student-modal.vue')['default']
    DeveloperList: typeof import('./components/developer/developer-list.vue')['default']
    InputDropdown: typeof import('./components/filter/part/input-dropdown.vue')['default']
    MainApartmentFilter: typeof import('./components/filter/main-apartment-filter.vue')['default']
    Map: typeof import('./components/map.vue')['default']
    MinMaxInputDropdown: typeof import('./components/filter/part/min-max-input-dropdown.vue')['default']
    NewDialogModal: typeof import('./components/site/modal/new-dialog-modal.vue')['default']
    PhoneInput: typeof import('./components/site/form/element/phone-input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectInput: typeof import('./components/site/form/element/select-input.vue')['default']
    SelectWithSearch: typeof import('./components/filter/part/select-with-search.vue')['default']
  }
}
