/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvantageItem: typeof import('./components/developer/advantage-item.vue')['default']
    Advantages: typeof import('./components/developer/advantages.vue')['default']
    AgentEdit: typeof import('./components/profile/agent/agent-edit.vue')['default']
    AgentList: typeof import('./components/profile/agent/agent-list.vue')['default']
    ApartmentItem: typeof import('./components/apartment/apartment-item.vue')['default']
    ApartmentList: typeof import('./components/apartment/apartment-list.vue')['default']
    AppFooter: typeof import('./components/site/footer/AppFooter.vue')['default']
    AppHeader: typeof import('./components/site/header/app-header.vue')['default']
    BuildObjectDetail: typeof import('./components/objects/build-object-detail.vue')['default']
    BuildObjectItem: typeof import('./components/objects/build-object-item.vue')['default']
    Button: typeof import('./components/site/button.vue')['default']
    BuyApartmentForm: typeof import('./components/site/form/buy-apartment-form.vue')['default']
    BuyApartmentModal: typeof import('./components/site/modal/buy-apartment-modal.vue')['default']
    Cabinet: typeof import('./components/site/cabinet.vue')['default']
    CatalogFilter: typeof import('./components/filter/catalog-filter.vue')['default']
    Chat: typeof import('./components/profile/chat/chat.vue')['default']
    ClaimDetail: typeof import('./components/profile/order/claim-detail.vue')['default']
    ClaimList: typeof import('./components/profile/element/claim-list.vue')['default']
    ClaimStatus: typeof import('./components/claim-status.vue')['default']
    ContactPersonalManager: typeof import('./components/site/modal/contact-personal-manager.vue')['default']
    CreateAgentModal: typeof import('./components/site/modal/create-agent-modal.vue')['default']
    CreateManagerModal: typeof import('./components/site/modal/create-manager-modal.vue')['default']
    CreateStudentModal: typeof import('./components/site/modal/create-student-modal.vue')['default']
    CurrentCity: typeof import('./components/site/header/current-city.vue')['default']
    DeveloperDashboard: typeof import('./components/profile/element/developer-dashboard.vue')['default']
    DeveloperList: typeof import('./components/developer/developer-list.vue')['default']
    DeveloperSearch: typeof import('./components/developer/developer-search.vue')['default']
    FastSearch: typeof import('./components/site/header/fast-search.vue')['default']
    FilterCheckbox: typeof import('./components/filter/part/filter-checkbox.vue')['default']
    GuestUserInformation: typeof import('./components/guest-user-information.vue')['default']
    Home: typeof import('./components/profile/home.vue')['default']
    ListWithSearch: typeof import('./components/filter/part/list-with-search.vue')['default']
    ManagerEdit: typeof import('./components/profile/manager/manager-edit.vue')['default']
    ManagerList: typeof import('./components/profile/manager/manager-list.vue')['default']
    Map: typeof import('./components/map.vue')['default']
    MenuHeader: typeof import('./components/site/header/menu-header.vue')['default']
    NewDialogModal: typeof import('./components/site/modal/new-dialog-modal.vue')['default']
    PersonalManager: typeof import('./components/profile/element/personal-manager.vue')['default']
    PhoneInput: typeof import('./components/site/form/element/phone-input.vue')['default']
    ProfileAsideMenu: typeof import('./components/profile/element/profile-aside-menu.vue')['default']
    ProfileEditForm: typeof import('./components/profile/element/profile-edit-form.vue')['default']
    ProfileLastView: typeof import('./components/profile/element/profile-last-view.vue')['default']
    ProfileOrderCostInfo: typeof import('./components/profile/element/profile-order-cost-info.vue')['default']
    ProfileReferral: typeof import('./components/profile/element/profile-referral.vue')['default']
    ProfileShortInfo: typeof import('./components/profile/element/profile-short-info.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectInput: typeof import('./components/site/form/element/select-input.vue')['default']
    ShortAgentList: typeof import('./components/profile/element/short-agent-list.vue')['default']
    ShortManagerList: typeof import('./components/profile/element/short-manager-list.vue')['default']
    ShortStudentList: typeof import('./components/profile/element/short-student-list.vue')['default']
    StudentList: typeof import('./components/student/StudentList.vue')['default']
    Table: typeof import('./components/table.vue')['default']
  }
}
