/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/developer/detail': RouteRecordInfo<'/developer/detail', '/developer/detail', Record<never, never>, Record<never, never>>,
    '/developer/list': RouteRecordInfo<'/developer/list', '/developer/list', Record<never, never>, Record<never, never>>,
    '/Index': RouteRecordInfo<'/Index', '/Index', Record<never, never>, Record<never, never>>,
    '/objects/detail': RouteRecordInfo<'/objects/detail', '/objects/detail', Record<never, never>, Record<never, never>>,
    '/objects/list': RouteRecordInfo<'/objects/list', '/objects/list', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/developer/detail.vue': {
      routes: '/developer/detail'
      views: never
    }
    'src/pages/developer/list.vue': {
      routes: '/developer/list'
      views: never
    }
    'src/pages/Index.vue': {
      routes: '/Index'
      views: never
    }
    'src/pages/objects/detail.vue': {
      routes: '/objects/detail'
      views: never
    }
    'src/pages/objects/list.vue': {
      routes: '/objects/list'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
