/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/developer/detail': RouteRecordInfo<'/developer/detail', '/developer/detail', Record<never, never>, Record<never, never>>,
    '/developer/list': RouteRecordInfo<'/developer/list', '/developer/list', Record<never, never>, Record<never, never>>,
    '/objects/detail': RouteRecordInfo<'/objects/detail', '/objects/detail', Record<never, never>, Record<never, never>>,
    '/objects/list': RouteRecordInfo<'/objects/list', '/objects/list', Record<never, never>, Record<never, never>>,
    '/profile/agent/detail': RouteRecordInfo<'/profile/agent/detail', '/profile/agent/detail', Record<never, never>, Record<never, never>>,
    '/profile/agent/list': RouteRecordInfo<'/profile/agent/list', '/profile/agent/list', Record<never, never>, Record<never, never>>,
    '/profile/education': RouteRecordInfo<'/profile/education', '/profile/education', Record<never, never>, Record<never, never>>,
    '/profile/home': RouteRecordInfo<'/profile/home', '/profile/home', Record<never, never>, Record<never, never>>,
    '/profile/manager/detail': RouteRecordInfo<'/profile/manager/detail', '/profile/manager/detail', Record<never, never>, Record<never, never>>,
    '/profile/manager/list': RouteRecordInfo<'/profile/manager/list', '/profile/manager/list', Record<never, never>, Record<never, never>>,
    '/profile/order/detail': RouteRecordInfo<'/profile/order/detail', '/profile/order/detail', Record<never, never>, Record<never, never>>,
    '/profile/order/list': RouteRecordInfo<'/profile/order/list', '/profile/order/list', Record<never, never>, Record<never, never>>,
    '/profile/settings': RouteRecordInfo<'/profile/settings', '/profile/settings', Record<never, never>, Record<never, never>>,
    '/profile/stream': RouteRecordInfo<'/profile/stream', '/profile/stream', Record<never, never>, Record<never, never>>,
    '/profile/student/list': RouteRecordInfo<'/profile/student/list', '/profile/student/list', Record<never, never>, Record<never, never>>,
    '/ref': RouteRecordInfo<'/ref', '/ref', Record<never, never>, Record<never, never>>,
    '/support': RouteRecordInfo<'/support', '/support', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/developer/detail.vue': {
      routes: '/developer/detail'
      views: never
    }
    'src/pages/developer/list.vue': {
      routes: '/developer/list'
      views: never
    }
    'src/pages/objects/detail.vue': {
      routes: '/objects/detail'
      views: never
    }
    'src/pages/objects/list.vue': {
      routes: '/objects/list'
      views: never
    }
    'src/pages/profile/agent/detail.vue': {
      routes: '/profile/agent/detail'
      views: never
    }
    'src/pages/profile/agent/list.vue': {
      routes: '/profile/agent/list'
      views: never
    }
    'src/pages/profile/education.vue': {
      routes: '/profile/education'
      views: never
    }
    'src/pages/profile/home.vue': {
      routes: '/profile/home'
      views: never
    }
    'src/pages/profile/manager/detail.vue': {
      routes: '/profile/manager/detail'
      views: never
    }
    'src/pages/profile/manager/list.vue': {
      routes: '/profile/manager/list'
      views: never
    }
    'src/pages/profile/order/detail.vue': {
      routes: '/profile/order/detail'
      views: never
    }
    'src/pages/profile/order/list.vue': {
      routes: '/profile/order/list'
      views: never
    }
    'src/pages/profile/settings.vue': {
      routes: '/profile/settings'
      views: never
    }
    'src/pages/profile/stream.vue': {
      routes: '/profile/stream'
      views: never
    }
    'src/pages/profile/student/list.vue': {
      routes: '/profile/student/list'
      views: never
    }
    'src/pages/ref.vue': {
      routes: '/ref'
      views: never
    }
    'src/pages/support.vue': {
      routes: '/support'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
