/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomFloatMenu: typeof import('./src/components/BottomFloatMenu.vue')['default']
    ListRequests: typeof import('./src/components/ListRequests.vue')['default']
    Registration: typeof import('./src/components/Registration.vue')['default']
  }
}
