/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    ApartmentFilter: typeof import('./src/components/ApartmentFilter.vue')['default']
    ApartmentItem: typeof import('./src/components/ApartmentItem.vue')['default']
    ApartmentList: typeof import('./src/components/ApartmentList.vue')['default']
    Auth: typeof import('./src/components/Auth.vue')['default']
    BottomFloatMenu: typeof import('./src/components/BottomFloatMenu.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    BuildObjectDetail: typeof import('./src/components/BuildObjectDetail.vue')['default']
    BuildObjectList: typeof import('./src/components/BuildObjectList.vue')['default']
    BuyApartmentForm: typeof import('./src/components/form/BuyApartmentForm.vue')['default']
    BuyApartmentModal: typeof import('./src/components/modal/BuyApartmentModal.vue')['default']
    CheckboxDropdown: typeof import('./src/components/filter/part/CheckboxDropdown.vue')['default']
    ClaimDetail: typeof import('./src/components/ClaimDetail.vue')['default']
    ClaimList: typeof import('./src/components/ClaimList.vue')['default']
    ClaimStatus: typeof import('./src/components/part/ClaimStatus.vue')['default']
    CurrentCity: typeof import('./src/components/CurrentCity.vue')['default']
    Developers: typeof import('./src/components/Developers.vue')['default']
    Init: typeof import('./src/components/system/Init.vue')['default']
    InputDropdown: typeof import('./src/components/filter/part/InputDropdown.vue')['default']
    MainApartmentFilter: typeof import('./src/components/filter/MainApartmentFilter.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    MaskInput: typeof import('./src/components/part/form/MaskInput.vue')['default']
    MinMaxInputDropdown: typeof import('./src/components/filter/part/MinMaxInputDropdown.vue')['default']
    PersonalManager: typeof import('./src/components/profile/PersonalManager.vue')['default']
    ProfileAsideMenu: typeof import('./src/components/ProfileAsideMenu.vue')['default']
    ProfileEditForm: typeof import('./src/components/ProfileEditForm.vue')['default']
    ProfileIndex: typeof import('./src/components/ProfileIndex.vue')['default']
    Registration: typeof import('./src/components/Registration.vue')['default']
    ShortOrderInfo: typeof import('./src/components/profile/ShortOrderInfo.vue')['default']
  }
}
