/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    Auth: typeof import('./src/components/Auth.vue')['default']
    BottomFloatMenu: typeof import('./src/components/BottomFloatMenu.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    BuildObjectsList: typeof import('./src/components/BuildObjectsList.vue')['default']
    Developers: typeof import('./src/components/Developers.vue')['default']
    ListClaims: typeof import('./src/components/ListClaims.vue')['default']
    ProfileAsideMenu: typeof import('./src/components/ProfileAsideMenu.vue')['default']
    ProfileEditForm: typeof import('./src/components/ProfileEditForm.vue')['default']
    Registration: typeof import('./src/components/Registration.vue')['default']
  }
}
